name: Test eco
on:
  push:
    paths:
      - "**.py"

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
      - name: Try to get manpages for cargo testing
        run: sudo apt install -y cargo
      - name: Run tests
        run: bash dev.sh --test
        working-directory: development/